// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskPublisher;

namespace TaskPublisher.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    partial class TaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("TaskPublisher.Packet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("hash")
                        .HasColumnType("TEXT");

                    b.Property<string>("message")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("sendDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("sended")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("packets");

                    b.HasData(
                        new
                        {
                            id = 1,
                            message = "message 1",
                            sendDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sended = false
                        },
                        new
                        {
                            id = 2,
                            message = "message 2",
                            sendDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sended = false
                        },
                        new
                        {
                            id = 3,
                            message = "message 3",
                            sendDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sended = false
                        },
                        new
                        {
                            id = 4,
                            message = "message 4",
                            sendDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sended = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
